version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/.presets/next"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/.presets/legacy/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "composer"
    directory: "/.presets/laravel"
    schedule:
      interval: "weekly"
    groups:
      composer-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "composer"
    directory: "/.presets/legacy"
    schedule:
      interval: "weekly"
    groups:
      composer-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/.docker/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/nginx"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.docker/tools"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/.docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
